### PR TITLE
Duty Blip change when inside a vehicle

### PR DESCRIPTION
**Pull request by AnishBplayz**
This PR is for enhancing QOL stuff and main objective for the change is

To differentiate the duty blip from in a vehicle and out of vehicle

So when you sit inside a vehicle the blip turns into a car and heads accordingly and vice versa when on foot it stays default.

### CODE REVIEW

**Review by Ranjit-Develops — APPROVED** [review]
Looks Good

**Review by Jamie9192 — CHANGES_REQUESTED** [review]
What is the reason for the local variable? could use if IsPedInAnyVehicle(ped) then

as its not used again?

**Comment by AnishBplayz** [comment]
There can be more additions done using this local variable and I don't think using a local variable to define that could be a big issue bruh

> What is the reason for the local variable? could use if IsPedInAnyVehicle(ped) then
> 
> as its not used again?

**Comment by Jamie9192** [comment]
> There can be more additions done using this local variable and I don't think using a local variable to define that could be a big issue bruh
> 
> > What is the reason for the local variable? could use if IsPedInAnyVehicle(ped) then
> > as its not used again?

No big issue at all. just pointless code bud

**Comment by Ranjit-Develops** [comment]
Yeah Actually Local Variable Is Used first If You want To save your Time and define it earlier

**Comment by Ranjit-Develops** [comment]
And If A Config would Be There It would be Pretty Nice 👍🏻

**Comment by r0adra93** [comment]
moved duty-blips to QB-Jobs

**Comment by AnishBplayz** [comment]
@r0adra93 Check qb-jobs PR added it there too for all the jobs but for time being until its unavailable to use people can use this for now and until then it can be merged too unless the code is wiped from here

**Pull request closed without merging**
