### PR TITLE
Moving to server side checks for inventory

### PR DESCRIPTION
**Pull request by r0adra93**
Security Fix for qb-policejob that coincides with inventory security fix located at: https://github.com/qbcore-framework/qb-inventory/pull/380

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

### CODE REVIEW

**Review by Irishstevie — APPROVED** [review]
I run this with qb-policejob: https://github.com/qbcore-framework/qb-policejob/pull/380

Tested storage Pull out cars open all the menus 

Works good

**Comment by SKITTLE6969** [comment]
Im getting this error after updating this along with the inventory :|
image

**Comment by r0adra93** [comment]
> Im getting this error after updating this along with the inventory :| image

Is this off a vanilla install of the core or do you have a bunch of addons?

**Comment by r0adra93** [comment]
> Im getting this error after updating this along with the inventory :| image

I am unable to reproduce on a vanilla install.
I had to update the inventory from github as the vanilla install doesn't include the latest merge.

However, this works as intended and expected with no errors.

**Review by Z3rio — CHANGES_REQUESTED** [review]
Anyone can give themselves all police items just by triggering the `police:server:addVehItems` event.
Here are the possible fixes for this:
- Use a callback instead of an event (easiest but not preferred fix)
- Create a table of all vehicle plates spawned through qb-policejob (someway) and check if the vehicle is in there, or simply check if the plate has the correct syntax
- Check if the vehicle model is correct (hardest but kinda best one)

**Comment by r0adra93** [comment]
> Anyone can give themselves all police items just by triggering the `police:server:addVehItems` event. Here are the possible fixes for this:
> 
> * Use a callback instead of an event (easiest but not preferred fix)
> * Create a table of all vehicle plates spawned through qb-policejob (someway) and check if the vehicle is in there, or simply check if the plate has the correct syntax
> * Check if the vehicle model is correct (hardest but kinda best one)

Qb-jobs resolves all these issues.
I'll reference it to make the changes here.

**Comment by Z3rio** [comment]
> > Anyone can give themselves all police items just by triggering the `police:server:addVehItems` event. Here are the possible fixes for this:
> > 
> > * Use a callback instead of an event (easiest but not preferred fix)
> > * Create a table of all vehicle plates spawned through qb-policejob (someway) and check if the vehicle is in there, or simply check if the plate has the correct syntax
> > * Check if the vehicle model is correct (hardest but kinda best one)
> 
> Qb-jobs resolves all these issues. I'll reference it to make the changes here.

Okay, but you do have to understand that I cant commit a PR with such security issue.

**Comment by r0adra93** [comment]
> > > Anyone can give themselves all police items just by triggering the `police:server:addVehItems` event. Here are the possible fixes for this:
> > > 
> > > * Use a callback instead of an event (easiest but not preferred fix)
> > > * Create a table of all vehicle plates spawned through qb-policejob (someway) and check if the vehicle is in there, or simply check if the plate has the correct syntax
> > > * Check if the vehicle model is correct (hardest but kinda best one)
> > 
> > 
> > Qb-jobs resolves all these issues. I'll reference it to make the changes here.
> 
> Okay, but you do have to understand that I cant commit a PR with such security issue.

That's fine i'll pull the trackVeh table, vehCount table and call backs from qb-jobs.

**Comment by r0adra93** [comment]
> > > Anyone can give themselves all police items just by triggering the `police:server:addVehItems` event. Here are the possible fixes for this:
> > > 
> > > * Use a callback instead of an event (easiest but not preferred fix)
> > > * Create a table of all vehicle plates spawned through qb-policejob (someway) and check if the vehicle is in there, or simply check if the plate has the correct syntax
> > > * Check if the vehicle model is correct (hardest but kinda best one)
> > 
> > 
> > Qb-jobs resolves all these issues. I'll reference it to make the changes here.
> 
> Okay, but you do have to understand that I cant commit a PR with such security issue.

I DID ALL OF THIS AND STILL NOT MERGED IN!

**Pull request closed without merging**
