### PR TITLE
Fix evidence stash access & prompt

### LINKED ISSUE #487: [BUG] Evidence Stashes Do Not Open
**Describe the bug**
Trying to open an evidence stash doesn't work. When you go to the marker, if qb-target is enabled, nothing pops up. If it's disabled, the "Evidence Stash | " pops up on the left side of the screen but only shows the incomplete %{value} next to it. It doesn't open the input menu to allow you to choose a stash.

**To Reproduce**
1. Go to your evidence locations
2. Try and interact with it
3. Fail

**This Is on The Newest Version of QB-PoliceJob**

### PR DESCRIPTION
**Pull request by citRaTTV**
**Describe Pull request**
Fixes #487 

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes]
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Comment by citRaTTV** [comment]
LINT errors are fixed in #491

**Comment by Nophobia09** [comment]
> **Describe Pull request**
> Fixes #487 
> 
> **Questions (please complete the following information):**
> - Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes]
> - Does your code fit the style guidelines? [yes]
> - Does your PR fit the contribution guidelines? [yes]
> 

@citRaTTV does this version keep the mouse cursor on screen when entering evidence stash? Or does it disappear? I'm unable to test this ATM, as I'm away for the holidays. I'll test when I return if you're unable to confirm.

**Comment by citRaTTV** [comment]
> > **Describe Pull request**
> > Fixes #487
> > **Questions (please complete the following information):**
> > 
> > * Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes]
> > * Does your code fit the style guidelines? [yes]
> > * Does your PR fit the contribution guidelines? [yes]
> 
> @citRaTTV does this version keep the mouse cursor on screen when entering evidence stash? Or does it disappear? I'm unable to test this ATM, as I'm away for the holidays. I'll test when I return if you're unable to confirm.

This doesn't change anything related to NUI focus, but I'll take a look

**Comment by citRaTTV** [comment]
> > > **Describe Pull request**
> > > Fixes #487
> > > **Questions (please complete the following information):**
> > > 
> > > * Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes]
> > > * Does your code fit the style guidelines? [yes]
> > > * Does your PR fit the contribution guidelines? [yes]
> > 
> > 
> > @citRaTTV does this version keep the mouse cursor on screen when entering evidence stash? Or does it disappear? I'm unable to test this ATM, as I'm away for the holidays. I'll test when I return if you're unable to confirm.
> 
> This doesn't change anything related to NUI focus, but I'll take a look

Cursor seems to stay on the screen
ow-overlay_yQc9uFtpeU

**Comment by Gongal014** [comment]
image
For me it appears like this and doesn't even open, can you help me?

**Comment by Nophobia09** [comment]
> image
> For me it appears like this and doesn't even open, can you help me?
> 

@Gongal014 

Try this one and let me know if it works for you. 

https://github.com/qbcore-framework/qb-policejob/issues/487#issuecomment-1854159290

**Comment by Gongal014** [comment]
Yes, it already did

**Comment by Nophobia09** [comment]
> Yes, it already did

@Gongal014 

It works now?

**Pull request merged**
