### PR TITLE
Compatibility with job types instead of using job name

### PR DESCRIPTION
**Pull request by tugamars**
Changed the script to be compatible with job types instead of using job names. This will put it alligned with latest qb-core version.

**Describe Pull request**
Having in mind the latest updates to qb-core, that introduced job types, to allow, for instance, multiple police departments without the need to copy-paste policejob and modify the job, i have modified the code to make it compatible with job types.

This will break for people who don't have their qb-core updated and update this script individually.

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] yes
- Does your code fit the style guidelines? Yes
- Does your PR fit the contribution guidelines? Yes

### CODE REVIEW

**Review by ag-izzy — COMMENTED** [review]
reasonable update for the benefit of the minority.
a logical option for a server that uses more than one law and order unit.

**Review by r0adra93 — APPROVED** [review]
code is working as edisplayed.
I am able to pull in vehicles, armory, etc with the job type and it's great.
It will go a great way in helping streamline operations for servers.

**Comment by GhzGarage** [comment]
Has conflicts

**Comment by tugamars** [comment]
> Has conflicts

This is weird considering i cloned the latest available version (at the time) and edited that, but i will take a look into fixing the conflicts.

**Comment by fuse9** [comment]
Can you make it so blips go from job name vs type so each department can be a different color blip?

**Review by i-kulgu — CHANGES_REQUESTED** [review]
Please update to the latest branch to avoid conflicts.

**Comment by r0adra93** [comment]
I am hamdlimg this change for qb-jobs.

**Comment by i-kulgu** [comment]
Send a PR with updated version and backward compatibility with older policejobs.

**Pull request closed without merging**
