### PR TITLE
better fine system and multijob

### PR DESCRIPTION
**Pull request by i-kulgu**
**Describe Pull request**

This pull request will add a better fine system where it controls if the money could be withdrawn from bank or cash if both fail it will create an invoice from qb-phone.
Also will this pull request add the possibility to setup multiple locations as LEO for SASP / LAPD / BCSO etc.
The indentation is also converted from tabs to 4 spaces.

If your PR is to fix an issue mention that issue here

#401 #337 #317  #375

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? No
- Does your code fit the style guidelines? Yes
- Does your PR fit the contribution guidelines? Yes

### CODE REVIEW

**Review by GlensowV5 — APPROVED** [review]

**Comment by r0adra93** [comment]
as far as multi-job is concerned this issue is being resolved with qb-jobs.

**Review by el-moxie — APPROVED** [review]
I am testing this for more than a month, and everything is working fine.
Thank you for this great change.

**Comment by i-kulgu** [comment]
Fixed the bug with spikes that you can place but not remove it anymore.

This will solve the issue with #333

**Comment by charj** [comment]
It's great that you are fixing these things, but it would be much easier to manage if these these were split into smaller seperate pr's

**Review by Draxaran — CHANGES_REQUESTED** [review]
So I managed to fix the jail command cause it wasn't actually jailing the person by removing PlayerJob.name == "police" all together and using leo but the issue I am still having is the fact the police armory will open but not show up the items for anything other than the police. It won't show for all leos also the garage only works for the police but not the other leos.

**Comment by r0adra93** [comment]
You need to change all the tabs to 4 spaces.

**Review by r0adra93 — CHANGES_REQUESTED** [review]
You need to change all the tabs to 4 spaces.
You need to fix your conflicts
you need to update your PR
you may want to break all these changes into separate Pull Requests.

**Pull request closed without merging**
