### PR TITLE
Add Multiple Helicopter Type Spawn Capability

### PR DESCRIPTION
**Pull request by DuoTheDev**
This PR serves as a new feature. In the QBCore Discord, a member had mentioned that they would like to have the ability to pull out different types of helicopters much like they can for cars. I have introduced that feature in this PR. 

**Things added:**
- The ability to add rank restrictions on helicopters
- The ability to add more than one police helicopter into the possible spawn pool
- The ability to use the cameras/ thermals/ night vision / etc with the newly added helicopters
- New text for the helicopter menu

**Things removed:**
- Text that was used to press E and spawn the polmav
- The now unused spawnHelicopter client event

### I am open to any feedback that anyone might have. Thank you!

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [**yes**] (Be honest)
- Does your code fit the style guidelines? [**yes**]
- Does your PR fit the contribution guidelines? [**yes**]

### CODE REVIEW

**Comment by DuoTheDev** [comment]
This PR also does not have the issue presented in https://github.com/qbcore-framework/qb-policejob/issues/443 . The helicopters do not stay after server restart. I do not think having a helicopter be deleted after player DC is a good idea due to potential head pops players may have. Would also cause some issues if there are cases where multiple helicopters need to be out at one time.

**Comment by YungT-SevsideRP** [comment]
Awsome, Thx So Much For Making This.

**Review by GodyFromDiscord — APPROVED** [review]
After some testing everything seems to work as intended and quite nicely, can confirm this works; LGTM

**Comment by r0adra93** [comment]
This feature is a feature set to be turned off with the release of qb-jobs.

**Review by r0adra93 — COMMENTED** [review]
This feature is a feature set to be turned off with the release of qb-jobs.

**Comment by gononono64** [comment]
Works good. Few minor complaints. Mostly with your combozone. 
-There is an unnecessary loop doing distance checks in your inout. See img[1] for an example fix
-I also noticed after i spawned in the helicopter at the location, the menu does not pop up to put the vehicle away until i leave the zone and re-enter.
-Zones do not get regenerated on resource restart
-This is probably further down the line but im getting an error message when the vehicle gets removed

image

**Comment by DuoTheDev** [comment]
> Seems to work. Few minor complaints. Mostly with your combozone.

Thanks for the comment. It was based off of existing code for the car garages and the old helicopter spawn... so chances are there might be things in there that are not ideal. I will definitely look into the points you've made to see if I can make improvements.

**Pull request closed without merging**
