### PR TITLE
added departments

### PR DESCRIPTION
**Pull request by Barmyyy**
Added SASP, BCSO

### CODE REVIEW

**Comment by jnccloud** [comment]
I like the effort but I think this should be heavily modified to support departments from the config file itself - hard coding them into the server/client isn't the solution anymore. The resource would need some decent refactoring to support separate locations in relationship to the job. I don't think this should be merged like this.

**Comment by Barmyyy** [comment]
> I like the effort but I think this should be heavily modified to support departments from the config file itself - hard coding them into the server/client isn't the solution anymore. The resource would need some decent refactoring to support separate locations in relationship to the job. I don't think this should be merged like this.

That is a really good idea. I will do that when I get the chance and then update this.

**Comment by Muri22** [comment]
i have issue with garage everyone takeout the vehicle from police

**Comment by L1quidSn4ke** [comment]
> i have issue with garage everyone can takeout the vehicle from police garage

This is an easy fix. Under the police section in qb-garages/config.lua make sure the police job is is set (line 227 for me)

type = 'job',                --public, job, gang, depot
vehicle = 'car',              --car, air, sea
job = "police"

**Comment by FjamZoo** [comment]
Sorry but this PR does not reflect the changes QBCore wants to see, if adding more departments or jobs to the police client it should not be done through the code but by Configs making a table that contains all the possible jobs and then loop through them with a function on the server and client file for ease of use.

I will close this PR, feel free to reopen one if you make the necesarry changes of making it easy to use through a config rather than the code.

**Pull request closed without merging**
