### PR TITLE
[UPDATE] Deprecate onDuty variable from qb-policejob

### PR DESCRIPTION
**Pull request by mmoftah**
**Describe Pull request**
Remove redundant onDuty variable used. Also removed that switching from another job to a police job will automatically clock you out, if clocked in. This doesn't make sense, especially for multijob scripts. If this was something needed, then it should be the default duty in the job shared lua and when the job is set it will automatically set the job duty.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest) yes
- Does your code fit the style guidelines? [yes/no] yes
- Does your PR fit the contribution guidelines? [yes/no] yes

### CODE REVIEW

**Comment by HezimX** [comment]
tested works :D
this also fixed bankrobery alarm

**Comment by AnishBplayz** [comment]
this works right... have tested it myself and is much better usage of function

**Comment by AnishBplayz** [comment]
Maybe @mmoftah  can you sync it with the latest Commits of Policejob ?

**Comment by mmoftah** [comment]
> Maybe @mmoftah can you sync it with the latest Commits of Policejob ?

done

**Review by AnishBplayz — APPROVED** [review]
All good everything works right !! **PR can be merged**

**Comment by AnishBplayz** [comment]
Why not try it for ambulancejob too...?

**Comment by mmoftah** [comment]
> Why not try it for ambulancejob too...?

If I can get one merged I can do the other 🤣

**Comment by AnishBplayz** [comment]
acceptable... hope some reviewer does it asap....

**Review by i-kulgu — COMMENTED** [review]
Can you please sync it with the latest branch ?
I have done it manually to the latest version and it works without any problems.
So if you can update your branch then it can be merged.

**Comment by mmoftah** [comment]
> Can you please sync it with the latest branch ? I have done it manually to the latest version and it works without any problems. So if you can update your branch then it can be merged.

rebased.

**Review by Z3rio — APPROVED** [review]
LGTM

**Pull request merged**
