### PR TITLE
spikestrip fix

### PR DESCRIPTION
**Pull request by nxte-development**
Fix for issue : https://github.com/qbcore-framework/qb-policejob/issues/333
- you can always pick up the spike strip
- other officers can also pick up the spike strips

- Following code needs to be added to qb-core/shared/items.lua
`
['spikestrip'] 				     = {['name'] = 'spikestrip',					['label'] = 'Spikestrip', 				['weight'] = 100, 		['type'] = 'item', 		['image'] = 'spikestrip.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Might be useful when someone is driving recklessly'},`

### CODE REVIEW

**Comment by Z3rio** [comment]
You have multiple linting issues + you dont need all of those random comments in the "DeployStinger", they add nothing to the code, nor do they really make the code more understandable.
Most FiveM scripts dont really need excessive comments since the natives are anyways english words that explain themselves.

**Comment by nxte-development** [comment]
Okay i'll rework it :) thanks for the info

**Comment by nxte-development** [comment]
and what are lint errors ? never used lint before :) @Z3rio

**Comment by Z3rio** [comment]
> and what are lint errors ? never used lint before :) @Z3rio

Linting is a word for formatting in coding.

Click on details next to the lint report and you will see the exact issues.

image
image

**Comment by Z3rio** [comment]
> Okay i'll rework it :) thanks for the info

Yeah, you dont need to rework everything. Just make sure you dont over use comments.
And if you are over using comments, you should ask your self, "Is this code readable without this comment?"
If it is readable without the comment, then the comment most likely shouldnt be there.

**Pull request closed without merging**
