### PR TITLE
Fingerprint scanner showing name

### PR DESCRIPTION
**Pull request by iiKline**
I got asked how to add the name to the fingerprint scanner and saw someone say the were looking into it. A friend and I already did this so I decided to PR it.

### CODE REVIEW

**Comment by nzkfc** [comment]
L E G E N D!

**Comment by Wafflzdev** [comment]
Anyone using this and can confirm that it works?

**Review by CptNoHand — APPROVED** [review]
Tested it on an up-to-date policejob and it works without problems.

**Review by ansljeremy — APPROVED** [review]
Tested on live server and works flawlessly

**Review by i-kulgu — CHANGES_REQUESTED** [review]
Please update to the latest branch to avoid conflicts.

**Review by JackWemble — APPROVED** [review]

**Comment by ggfto** [comment]
@itsKline Can you update the branch with the latest version please? Then I'll ask to merge this PR.

**Comment by itsKline** [comment]
> @itsKline Can you update the branch with the latest version please? Then I'll ask to merge this PR.

This PR was made 9 months ago, I will not be updating it. Y'all can either update it or you can just close the PR

**Pull request closed without merging**
