### PR TITLE
Adding animation and notifications to SearchPlayer event

### PR DESCRIPTION
**Pull request by DHoogland**
**Describe Pull request**
Updated the SearchPlayer event with progressbar, animation and notifications. I feel like this should be part of qb-policejob, so users don't have to make this themselves. 

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes]
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Review by TrooperGarry11 — APPROVED** [review]

**Comment by FjamZoo** [comment]
Please include the locale system within your PR as I see "Cancelled" and "Noone is around" is not using the locales.

**Comment by jnccloud** [comment]
Tested this without paying attention to the animation. Pretty weird to have a cop hold someone up to search them... found out the hard way lol

**Review by NoobySloth — CHANGES_REQUESTED** [review]
Please use locales as per added, I've also changed the animation so it doesn't look like a police officer is holding a civilian up. There is probably better animations but I'm not sure...

```lua
RegisterNetEvent('police:client:SearchPlayer', function()
    local player, distance = QBCore.Functions.GetClosestPlayer()
    local ped = PlayerPedId()
    if player ~= -1 and distance < 2.5 then
        local playerPed = GetPlayerPed(player)
        local playerId = GetPlayerServerId(player)
            QBCore.Functions.Progressbar("search_player", "Searching person..", math.random(5000, 7000), false, true, {
                disableMovement = false,
                disableCarMovement = false,
                disableMouse = false,
                disableCombat = false,
            }, {
                animDict = "mini@repair",
                anim = "fixing_a_ped",
                flags = 16,
            }, {}, {}, function() -- Done
                local plyCoords = GetEntityCoords(playerPed)
                local pos = GetEntityCoords(ped)
                if #(pos - plyCoords) < 2.5 then
                    StopAnimTask(ped, "mini@repair", "fixing_a_ped", 1.0)
                    TriggerServerEvent("inventory:server:OpenInventory", "otherplayer", playerId)
                    TriggerServerEvent("police:server:SearchPlayer", playerId)
                else
                    QBCore.Functions.Notify(Lang:t("error.none_nearby"), "error")
                end
            end, function() -- Cancel
                StopAnimTask(ped, "mini@repair", "fixing_a_ped", 1.0)
                QBCore.Functions.Notify(Lang:t("error.canceled"), "error")
            end)
    else
        QBCore.Functions.Notify(Lang:t("error.none_nearby"), "error")
    end
end)

**Comment by FjamZoo** [comment]
Please update this branch since its out of date.

**Comment by FjamZoo** [comment]
Havent updated this PR for almost a month after being requested if you want this implement reopen the PR.

**Pull request closed without merging**
