### PR TITLE
No armory whitelist for the police force

### PR DESCRIPTION
**Pull request by BerkieBb**

### CODE REVIEW

**Review by ImpulseFPS — CHANGES_REQUESTED** [review]
why are you using grades at all here?
Give all players that have police job access to the armory
or at least add few grades to it not just one. lol

**Comment by BerkieBb** [comment]
Because the first way it is supposed to be is it required the boss of the police to be online, so I made that with grades

**Comment by ImpulseFPS** [comment]
No, it was the only specified citizenid can use the armory, this was you are limiting it to one grade only

**Comment by BerkieBb** [comment]
Alright then if you really want to I'll add grade 2 and 3 to it

**Pull request closed without merging**
