### PR TITLE
Added PolyZone and Target support

### PR DESCRIPTION
**Pull request by mk3ext**
**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

### CODE REVIEW

**Comment by mk3ext** [comment]
Relates to #268

**Comment by BerkieBb** [comment]
Should put Config.UseTarget to false by default

**Comment by mk3ext** [comment]
> Should put Config.UseTarget to false by default

Forgot to revert that from when I was debugging, thanks for the spot!

**Comment by milotiro95** [comment]
I tried it on my policejob but had qbcore error after using it.

**Comment by Andyauk** [comment]
helicopterZones and most of the box_zone are too long, I see you have  10, 10 and a few 5 , 1. but if you turn debug on, they are massive beams. great work though

**Comment by BerkieBb** [comment]
Conflicts

**Comment by trclassic92** [comment]
While looking at the changes I noticed that the locales weren't updated to the new draw text ui interaction.. I will post an example of what I mean is

```[~g~E~s~] - Go on duty``` [~g~E~s~] is no longer needed. It can be changed to ```[E] - Go on duty``` instead.

Also, TakeOutVehicle and TakeOutImpound are still using a distance check which is no longer needed if you are using a polyzone.

**Comment by Andyauk** [comment]
helicopter could do with a put away like the cars,  and some of the interactions can be triggered, so I guess the polys are still too big, i.e. I could trigger fingerprint on the roof on PD, when I have fingerprint set up near the cells. but in all its, very good.

Tomorrow I will turn polys on to have a look, as it could just mean I need to move something.
ill upload a photo also.

**Comment by mk3ext** [comment]
> helicopter could do with a put away like the cars, and some of the interactions can be triggered, so I guess the polys are still too big, i.e. I could trigger fingerprint on the roof on PD, when I have fingerprint set up near the cells. but in all its, very good.
> 
> Tomorrow I will turn polys on to have a look, as it could just mean I need to move something. ill upload a photo also.

Will get around to this either later today or tomorrow

**Comment by Andyauk** [comment]
> > helicopter could do with a put away like the cars, and some of the interactions can be triggered, so I guess the polys are still too big, i.e. I could trigger fingerprint on the roof on PD, when I have fingerprint set up near the cells. but in all its, very good.
> > Tomorrow I will turn polys on to have a look, as it could just mean I need to move something. ill upload a photo also.
> 
> Will get around to this either later today or tomorrow

thanks, do you want screenshots?
keep up the great work

**Comment by JUSTIN-VIKKY** [comment]
Seems like someone forgot a min and max z

getting E option here
Screenshot (775)

**Comment by JUSTIN-VIKKY** [comment]
Getting evidence stash here 
Screenshot (776)

**Comment by MontysQi** [comment]
Why on gods green earth would you guys get rid of Drawmarkers? This resource was perfect with the drawmarkers can we please can them back?

**Pull request merged**
