### PR TITLE
Use LEO for job types

### PR DESCRIPTION
**Pull request by i-kulgu**
**Describe Pull request**

Police system will also use job type LEO.
This way you can use policejob for multiple departments and setup multiple places.

If your PR is to fix an issue mention that issue here

https://github.com/qbcore-framework/qb-policejob/issues/401 https://github.com/qbcore-framework/qb-policejob/issues/337  https://github.com/qbcore-framework/qb-policejob/issues/375

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [Yes]
- Does your code fit the style guidelines? [Yes]
- Does your PR fit the contribution guidelines? [Yes]

### CODE REVIEW

**Review by r0adra93 — APPROVED** [review]

**Comment by zwkf** [comment]
So this is nice.
As there's lots of occurances of `PlayerJob.name == 'police' or PlayerJob.type == 'leo'`
I wonder if we could have a reusable function called something like `isValidJobType(jobType)`

This function could check if the passed `jobType` exists in an array and return a boolean

Just an idea but will make maintaining these easier going forward

**Comment by i-kulgu** [comment]
> So this is nice. As there's lots of occurances of `PlayerJob.name == 'police' or PlayerJob.type == 'leo'` I wonder if we could have a reusable function called something like `isValidJobType(jobType)`
> 
> This function could check if the passed `jobType` exists in an array and return a boolean
> 
> Just an idea but will make maintaining these easier going forward

I was thinking about the same.
Gonna make a function today and update the PR

**Comment by r0adra93** [comment]
Be mindful of where it asks for a false instead of true
However running the function will do the same thing in this case.

Instead of lessening the number of if statements we are doubling the number...

Every time the function runs that's another if statement being run.

I am thinking either a table or grouping all the if positives together into a single if statement.

**Comment by r0adra93** [comment]
We need to get this current version pushed as is.
Qb-jobs is nearing completion and we need to get these resources pushed.

We can look into rewriting this respurce after this current pr is merged.

**Comment by i-kulgu** [comment]
> Qb-jobs is nearing completion and we need to get these resources pushed.
> 
> We can look into rewriting this respurce after this current pr is merged.

Maybe just leave it as is because when we introduce the job type we can delete the other jobs and use only the type instead of job name. Almost everyone has already the jobtype in their qb-core\shared\jobs

**Comment by i-kulgu** [comment]
Not merging and i won't update it.
If needed you can get the codes.

**Pull request closed without merging**
