### PR TITLE
Prevent Civs from pulling out vehicles from impound and heli

### PR DESCRIPTION
**Pull request by zWyzzzzz**
**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

### CODE REVIEW

**Comment by FjamZoo** [comment]
I believe there's multiple ones missing this such as helicopter, garages etc. could you please update all these?

**Comment by zWyzzzzz** [comment]
> I believe there's multiple ones missing this such as helicopter, garages etc. could you please update all these?

yes i can

**Comment by FjamZoo** [comment]
Hey there, new feature got moved into qbcore so instead of doing

`PlayerJob.name == "police"` please use `PlayerJob.type == "leo"`

**Comment by zWyzzzzz** [comment]
> Hey there, new feature got moved into qbcore so instead of doing
> 
> `PlayerJob.name == "police"` please use `PlayerJob.type == "leo"`

so this for multi police job?

**Comment by FjamZoo** [comment]
> > Hey there, new feature got moved into qbcore so instead of doing
> > `PlayerJob.name == "police"` please use `PlayerJob.type == "leo"`
> 
> so this for multi police job?

Yes

**Review by FjamZoo — APPROVED** [review]

**Pull request closed without merging**
